version: '3.8'

services:
  gait-analysis:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../logs:/app/logs
      - ../reports:/app/reports
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - gait-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - gait-analysis
    restart: unless-stopped
    networks:
      - gait-network

networks:
  gait-network:
    driver: bridge

volumes:
  gait-data:
  gait-models:
  gait-logs:
